// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import java.io.Serializable;
import jp.com.inotaku.domain.Sale;

privileged aspect Sale_Roo_Serializable {
    
    declare parents: Sale implements Serializable;
    
    private static final long Sale.serialVersionUID = 1L;
    
}
