// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.com.inotaku.domain.SaleDataOnDemand;
import jp.com.inotaku.domain.SaleIntegrationTest;
import jp.com.inotaku.repository.SaleRepository;
import jp.com.inotaku.service.SaleService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SaleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SaleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SaleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SaleIntegrationTest: @Transactional;
    
    @Autowired
    SaleDataOnDemand SaleIntegrationTest.dod;
    
    @Autowired
    SaleService SaleIntegrationTest.saleService;
    
    @Autowired
    SaleRepository SaleIntegrationTest.saleRepository;
    
    @Test
    public void SaleIntegrationTest.testCountAllSales() {
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", dod.getRandomSale());
        long count = saleService.countAllSales();
        Assert.assertTrue("Counter for 'Sale' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SaleIntegrationTest.testFindSale() {
        Sale obj = dod.getRandomSale();
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sale' failed to provide an identifier", id);
        obj = saleService.findSale(id);
        Assert.assertNotNull("Find method for 'Sale' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sale' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SaleIntegrationTest.testFindAllSales() {
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", dod.getRandomSale());
        long count = saleService.countAllSales();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sale', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sale> result = saleService.findAllSales();
        Assert.assertNotNull("Find all method for 'Sale' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sale' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SaleIntegrationTest.testFindSaleEntries() {
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", dod.getRandomSale());
        long count = saleService.countAllSales();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sale> result = saleService.findSaleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sale' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sale' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SaleIntegrationTest.testFlush() {
        Sale obj = dod.getRandomSale();
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sale' failed to provide an identifier", id);
        obj = saleService.findSale(id);
        Assert.assertNotNull("Find method for 'Sale' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySale(obj);
        Integer currentVersion = obj.getVersion();
        saleRepository.flush();
        Assert.assertTrue("Version for 'Sale' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaleIntegrationTest.testUpdateSaleUpdate() {
        Sale obj = dod.getRandomSale();
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sale' failed to provide an identifier", id);
        obj = saleService.findSale(id);
        boolean modified =  dod.modifySale(obj);
        Integer currentVersion = obj.getVersion();
        Sale merged = saleService.updateSale(obj);
        saleRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Sale' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaleIntegrationTest.testSaveSale() {
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", dod.getRandomSale());
        Sale obj = dod.getNewTransientSale(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sale' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sale' identifier to be null", obj.getId());
        try {
            saleService.saveSale(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        saleRepository.flush();
        Assert.assertNotNull("Expected 'Sale' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SaleIntegrationTest.testDeleteSale() {
        Sale obj = dod.getRandomSale();
        Assert.assertNotNull("Data on demand for 'Sale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sale' failed to provide an identifier", id);
        obj = saleService.findSale(id);
        saleService.deleteSale(obj);
        saleRepository.flush();
        Assert.assertNull("Failed to remove 'Sale' with identifier '" + id + "'", saleService.findSale(id));
    }
    
}
