// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import jp.com.inotaku.domain.SaleDetailsDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SaleDetailsDataOnDemand_Roo_Configurable {
    
    declare @type: SaleDetailsDataOnDemand: @Configurable;
    
}
