// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.com.inotaku.domain.SaleDetailDataOnDemand;
import jp.com.inotaku.domain.SaleDetailIntegrationTest;
import jp.com.inotaku.repository.SaleDetailRepository;
import jp.com.inotaku.service.SaleDetailService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SaleDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SaleDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SaleDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SaleDetailIntegrationTest: @Transactional;
    
    @Autowired
    SaleDetailDataOnDemand SaleDetailIntegrationTest.dod;
    
    @Autowired
    SaleDetailService SaleDetailIntegrationTest.saleDetailService;
    
    @Autowired
    SaleDetailRepository SaleDetailIntegrationTest.saleDetailRepository;
    
    @Test
    public void SaleDetailIntegrationTest.testCountAllSaleDetails() {
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", dod.getRandomSaleDetail());
        long count = saleDetailService.countAllSaleDetails();
        Assert.assertTrue("Counter for 'SaleDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SaleDetailIntegrationTest.testFindSaleDetail() {
        SaleDetail obj = dod.getRandomSaleDetail();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to provide an identifier", id);
        obj = saleDetailService.findSaleDetail(id);
        Assert.assertNotNull("Find method for 'SaleDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SaleDetail' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SaleDetailIntegrationTest.testFindAllSaleDetails() {
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", dod.getRandomSaleDetail());
        long count = saleDetailService.countAllSaleDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'SaleDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SaleDetail> result = saleDetailService.findAllSaleDetails();
        Assert.assertNotNull("Find all method for 'SaleDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SaleDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SaleDetailIntegrationTest.testFindSaleDetailEntries() {
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", dod.getRandomSaleDetail());
        long count = saleDetailService.countAllSaleDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SaleDetail> result = saleDetailService.findSaleDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SaleDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SaleDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SaleDetailIntegrationTest.testFlush() {
        SaleDetail obj = dod.getRandomSaleDetail();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to provide an identifier", id);
        obj = saleDetailService.findSaleDetail(id);
        Assert.assertNotNull("Find method for 'SaleDetail' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySaleDetail(obj);
        Integer currentVersion = obj.getVersion();
        saleDetailRepository.flush();
        Assert.assertTrue("Version for 'SaleDetail' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaleDetailIntegrationTest.testUpdateSaleDetailUpdate() {
        SaleDetail obj = dod.getRandomSaleDetail();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to provide an identifier", id);
        obj = saleDetailService.findSaleDetail(id);
        boolean modified =  dod.modifySaleDetail(obj);
        Integer currentVersion = obj.getVersion();
        SaleDetail merged = saleDetailService.updateSaleDetail(obj);
        saleDetailRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SaleDetail' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaleDetailIntegrationTest.testSaveSaleDetail() {
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", dod.getRandomSaleDetail());
        SaleDetail obj = dod.getNewTransientSaleDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SaleDetail' identifier to be null", obj.getId());
        try {
            saleDetailService.saveSaleDetail(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        saleDetailRepository.flush();
        Assert.assertNotNull("Expected 'SaleDetail' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SaleDetailIntegrationTest.testDeleteSaleDetail() {
        SaleDetail obj = dod.getRandomSaleDetail();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SaleDetail' failed to provide an identifier", id);
        obj = saleDetailService.findSaleDetail(id);
        saleDetailService.deleteSaleDetail(obj);
        saleDetailRepository.flush();
        Assert.assertNull("Failed to remove 'SaleDetail' with identifier '" + id + "'", saleDetailService.findSaleDetail(id));
    }
    
}
